name: Refresh docker NuGet cache

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "8.8.x"
        type: choice
        options:
          - "8.8.x"
          - "8.6.x"
      image:
        description: "Image"
        required: true
        default: "ubuntu"
        type: choice
        options:
          - "ubuntu"
          - "centos"

jobs:
  build:
    strategy:
      matrix:
        branch: ["8.8.x", "8.6.x"]
        image:
          [
            "ubuntu-hpcc",
            "ubuntu-18.04",
            "ubuntu-20.04",
            "ubuntu-22.04",
            "centos-7",
            "centos-8",
          ]
      fail-fast: false

    name: "${{ matrix.image }}-${{ matrix.branch }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: "Build dockerfile"
        working-directory: .
        shell: "bash"
        run: |
          GITHUB_REF=$(git ls-remote https://github.com/hpcc-systems/vcpkg refs/heads/hpcc-platform-${{ matrix.branch }} | cut -f 1)
          docker build --pull --rm -f "dockerfiles/${{ matrix.image }}.dockerfile" -t vcpkg-${{ matrix.image }}:$GITHUB_REF "dockerfiles" \
          --build-arg GITHUB_REF=$GITHUB_REF \
          --build-arg GITHUB_ACTOR=${{ github.actor }} \
          --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
