name: Refresh NuGet cache

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  push:
    branches:
      - "main"

  schedule:
    - cron: "0 0,6,12,18 * * *"

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "8.12.x"
        type: choice
        options:
          - "8.12.x"
          - "8.8.x"
          - "8.6.x"
      os:
        description: "OS"
        required: true
        default: "ubuntu-20.04"
        type: choice
        options:
          - "ubuntu-18.04"
          - "ubuntu-20.04"
          - "ubuntu-22.04"
          - "windows-2019"
          - "windows-2022"
          - "macos-11"
          - "macos-12"

jobs:
  build:
    strategy:
      matrix:
        branch: ["8.12.x", "8.8.x", "8.6.x"]
        label:
          [
            "ubuntu-18.04-x64",
            "ubuntu-20.04-x64",
            "ubuntu-22.04-x64",
            "windows-2019-x64",
            "windows-2019-x86",
            "windows-2022-x64",
            "windows-2022-x86",
            "macos-11-x64",
            "macos-12-x64",
          ]
        include:
          - label: "ubuntu-18.04-x64"
            os: "ubuntu-18.04"
            triplet: "x64-linux"
            mono: "mono"
            sudo: "sudo"
            logs: "/usr/local/share/vcpkg"
          - label: "ubuntu-20.04-x64"
            os: "ubuntu-20.04"
            triplet: "x64-linux"
            mono: "mono"
            sudo: "sudo"
            logs: "/usr/local/share/vcpkg"
          - label: "ubuntu-22.04-x64"
            os: "ubuntu-22.04"
            triplet: "x64-linux"
            mono: "mono"
            sudo: "sudo"
            logs: "/usr/local/share/vcpkg"
          - label: "windows-2019-x64"
            os: "windows-2019"
            triplet: "x64-windows"
            mono: ""
            sudo: ""
            logs: "C:/vcpkg"
          - label: "windows-2019-x86"
            os: "windows-2019"
            triplet: "x86-windows"
            mono: ""
            sudo: ""
            logs: "C:/vcpkg"
          - label: "windows-2022-x64"
            os: "windows-2022"
            triplet: "x64-windows"
            mono: ""
            sudo: ""
            logs: "C:/vcpkg"
          - label: "windows-2022-x86"
            os: "windows-2022"
            triplet: "x86-windows"
            mono: ""
            sudo: ""
            logs: "C:/vcpkg"
          - label: "macos-11-x64"
            os: "macos-11"
            triplet: "x64-osx"
            mono: "mono"
            sudo: "sudo"
            logs: "/usr/local/share/vcpkg"
          - label: "macos-12-x64"
            os: "macos-12"
            triplet: "x64-osx"
            mono: "mono"
            sudo: "sudo"
            logs: "/usr/local/share/vcpkg"
      fail-fast: false

    name: "${{ matrix.label }} - ${{ matrix.branch }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Ubuntu Dependencies
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: "bash"
        run: |
          sudo apt-get update -y
          sudo apt-get install -yq --no-install-recommends \
            apt-transport-https \
            autoconf \
            autoconf-archive \
            automake \
            autotools-dev \
            binutils-dev \
            bison \
            build-essential \
            ca-certificates \
            curl \
            dirmngr \
            flex \
            git \
            gnupg \
            groff-base \
            libtool \
            pkg-config \
            software-properties-common \
            tar \
            unzip \
            uuid-dev \
            zip

      - name: OSX Dependencies
        if: ${{ matrix.os == 'macos-11' || matrix.os == 'macos-12'}}
        shell: "bash"
        run: |
          brew install pkg-config autoconf autoconf-archive automake libtool

      - name: "Setup NuGet Sources"
        shell: "bash"
        run: |
          ${{ matrix.mono }} `vcpkg fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "${{ github.repository_owner }}" \
            -password "${{ secrets.GITHUB_TOKEN }}"

      - name: "Setup NuGet API key"
        shell: "bash"
        run: |
          ${{ matrix.mono }} `vcpkg fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: "Remove builtin vcpkg (old)"
        shell: "bash"
        run: |
          ${{ matrix.sudo }} rm -rf "$VCPKG_INSTALLATION_ROOT"

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          ref: hpcc-platform-${{ matrix.branch }}
          submodules: recursive

      - name: "Bootstrap vcpkg"
        shell: "bash"
        run: |
          ./bootstrap-vcpkg.sh

      - name: "Update nuget (overlays)"
        if: ${{ !contains(matrix.os, 'ubuntu') || matrix.branch != '8.12.x' }}
        shell: "bash"
        run: |
          ./vcpkg install --overlay-ports=overlays --keep-going  --triplet=${{ matrix.triplet }}

      - name: "Update nuget (overlays) 8.12.x"
        if: ${{ contains(matrix.os, 'ubuntu') && matrix.branch == '8.12.x' }}
        shell: "bash"
        run: |
          ./vcpkg install --overlay-ports=overlays --keep-going  --triplet=${{ matrix.triplet }}-dynamic

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ matrix.label }}-logs
          path: ${{ matrix.logs }}/buildtrees/*/*.log
